'use strict';module.exports = { 
  graphTransformations: [
  'addDefinitionToGraph', 
  'addOperatorTypeAnnotation', 
  'referentialTransparency', 
  'linkInteractionsToDefinitions', 
  'addInterfaceInformationToInteractions', 
  'expandDefinitions', 
  'removeNonRootDefinitions', 
  'clearSubInformation', 
  'instantiateInterfaces', 
  'linkArguments', 
  'linkInterface', 
  'keepOnlyInteractions', 
  'referentialTransparencyInstances', 
  'linkIdentifiers', 
  'voidInteractionCreation', 
  'behaviourSeparation', 
  'functionLiteralLinking', 
  'dataLiteralLinking', 
  'functionApplicationLinking', 
  'previousNextLinking', 
  'tagCompositionElementEdges', 
  'matchingCompositionReduction', 
  'removeOneSidedAffectation', 
  'createDataFlowDirection', 
  'nonMatchingCompositionCompilation', 
  'affectationLinking', 
  'removeDuplicateEdge', 
  'resolveMultiplePorts', 
  'instantiateTemplates', 
  'orderGraph', 
  'keepOnlyOrdering', 
  'graphTransformationPipeline', 
  'getJsCode', 
  'getExpandedLidlCode', 
  'getInteractionMetrics', 
  'error'] };