"use strict";module.exports = (function () {
  "use strict"

  /*
   * Generated by PEG.js 0.9.0.
   *
   * http://pegjs.org/
   */;

  function peg$subclass(child, parent) {
    function ctor() {this.constructor = child;}
    ctor.prototype = parent.prototype;
    child.prototype = new ctor();}


  function peg$SyntaxError(message, expected, found, location) {
    this.message = message;
    this.expected = expected;
    this.found = found;
    this.location = location;
    this.name = "SyntaxError";

    if (typeof Error.captureStackTrace === "function") {
      Error.captureStackTrace(this, peg$SyntaxError);}}



  peg$subclass(peg$SyntaxError, Error);

  function peg$parse(input) {
    var options = arguments.length > 1 ? arguments[1] : {}, 
    parser = this, 

    peg$FAILED = {}, 

    peg$startRuleFunctions = { start: peg$parsestart, interaction: peg$parseinteraction, interfac: peg$parseinterfac, data: peg$parsedata, interactionDefinition: peg$parseinteractionDefinition }, 
    peg$startRuleFunction = peg$parsestart, 

    peg$c0 = function peg$c0(definitions) {return definitions;}, 
    peg$c1 = { type: "other", description: "a list of definitions" }, 
    peg$c2 = function peg$c2(content) {return flatten(content);}, 
    peg$c3 = { type: "other", description: "a definition or an import statement" }, 
    peg$c4 = function peg$c4(theInteractionDefinition) {return [theInteractionDefinition];}, 
    peg$c5 = function peg$c5(theInterfaceDefinition) {return [theInterfaceDefinition];}, 
    peg$c6 = function peg$c6(theDataDefinition) {return [theDataDefinition];}, 
    peg$c7 = "import", 
    peg$c8 = { type: "literal", value: "import", description: "\"import\"" }, 
    peg$c9 = /^[^`]/, 
    peg$c10 = { type: "class", value: "[^`]", description: "[^`]" }, 
    peg$c11 = function peg$c11(filename) {return parse(fs.readFileSync(filename.join(''), { encoding: 'utf8' }));}, 
    peg$c12 = { type: "other", description: "an interaction definition" }, 
    peg$c13 = "interaction", 
    peg$c14 = { type: "literal", value: "interaction", description: "\"interaction\"" }, 
    peg$c15 = "with", 
    peg$c16 = { type: "literal", value: "with", description: "\"with\"" }, 
    peg$c17 = function peg$c17(signature, definitions) {return definitions;}, 
    peg$c18 = "is", 
    peg$c19 = { type: "literal", value: "is", description: "\"is\"" }, 
    peg$c20 = function peg$c20(signature, definitions, interaction) {
      var res = { 
        type: 'InteractionDefinition', 
        interaction: interaction, 
        signature: signature, 
        definitions: definitions === null ? [] : definitions, 
        meta: { location: location(), options: options } };

      var arrayLength = res.definitions.length;
      for (var i = 0; i < arrayLength; i++) {
        res.definitions[i].parent = res;}

      return res;}, 

    peg$c21 = { type: "other", description: "an interaction interactionSignature specification" }, 
    peg$c22 = "(", 
    peg$c23 = { type: "literal", value: "(", description: "\"(\"" }, 
    peg$c24 = ")", 
    peg$c25 = { type: "literal", value: ")", description: "\")\"" }, 
    peg$c26 = ":", 
    peg$c27 = { type: "literal", value: ":", description: "\":\"" }, 
    peg$c28 = function peg$c28(elements, interfac) {var temp = mergeSignature(elements);return { type: 'InteractionSignature', interfac: interfac, formating: temp.operator, operator: temp.operator.replace(
        //  /[ \t\r\n]*\$[ \t\r\n]*/g,"$"
        /[ \t\r\n]*/g, ""), 
        operand: temp.operand, meta: { location: location(), options: options } };}, 
    peg$c29 = { type: "other", description: "a interactionSignature element" }, 
    peg$c30 = function peg$c30(operator) {return { operator: operator };}, 
    peg$c31 = function peg$c31(name, interfac) {return { operand: { type: 'InteractionSignatureOperandElement', interfac: interfac, name: name, meta: { location: location(), options: options } } };}, 
    peg$c32 = { type: "other", description: "an interaction" }, 
    peg$c33 = function peg$c33(elements) {var temp = mergeExpression(elements);return { type: 'InteractionSimple', formating: temp.operator, operator: temp.operator.replace(
        //  /[ \t\r\n]*\$[ \t\r\n]*/g,"$"
        /[ \t\r\n]*/g, ""), 
        operand: temp.operand, meta: { location: location(), options: options } };}, 
    peg$c34 = { type: "other", description: "an interaction element" }, 
    peg$c35 = function peg$c35(operand) {return { operand: operand };}, 
    peg$c36 = { type: "other", description: "an interface definition" }, 
    peg$c37 = "interface", 
    peg$c38 = { type: "literal", value: "interface", description: "\"interface\"" }, 
    peg$c39 = function peg$c39(signature, definitions, interfac) {
      return { 
        type: 'InterfaceDefinition', 
        interfac: interfac, 
        signature: signature, 
        definitions: definitions === null ? [] : definitions, 
        meta: { location: location(), options: options } };}, 


    peg$c40 = { type: "other", description: "the specification of an interfac" }, 
    peg$c41 = { type: "other", description: "the specification of an interfac using operators" }, 
    peg$c42 = ",", 
    peg$c43 = { type: "literal", value: ",", description: "\",\"" }, 
    peg$c44 = function peg$c44(operator, first, content) {return content;}, 
    peg$c45 = function peg$c45(operator, first, rest) {return { type: "InterfaceOperation", operator: operator, operand: mergeElements(first, rest), meta: { location: location(), options: options } };}, 
    peg$c46 = { type: "other", description: "an interfac operator (conjugation,globalisation,localisation,reception,emission,union,intersection,complement)" }, 
    peg$c47 = "conjugation", 
    peg$c48 = { type: "literal", value: "conjugation", description: "\"conjugation\"" }, 
    peg$c49 = "globalisation", 
    peg$c50 = { type: "literal", value: "globalisation", description: "\"globalisation\"" }, 
    peg$c51 = "localisation", 
    peg$c52 = { type: "literal", value: "localisation", description: "\"localisation\"" }, 
    peg$c53 = "reception", 
    peg$c54 = { type: "literal", value: "reception", description: "\"reception\"" }, 
    peg$c55 = "emission", 
    peg$c56 = { type: "literal", value: "emission", description: "\"emission\"" }, 
    peg$c57 = "union", 
    peg$c58 = { type: "literal", value: "union", description: "\"union\"" }, 
    peg$c59 = "intersection", 
    peg$c60 = { type: "literal", value: "intersection", description: "\"intersection\"" }, 
    peg$c61 = "complement", 
    peg$c62 = { type: "literal", value: "complement", description: "\"complement\"" }, 
    peg$c63 = { type: "other", description: "the specification of an atomic interfac" }, 
    peg$c64 = function peg$c64(data, direction) {return { type: 'InterfaceAtomic', data: data, direction: direction, meta: { location: location(), options: options } };}, 
    peg$c65 = { type: "other", description: "the specification of a composite interfac" }, 
    peg$c66 = "{", 
    peg$c67 = { type: "literal", value: "{", description: "\"{\"" }, 
    peg$c68 = function peg$c68(key, value) {return { type: 'InterfaceCompositeElement', key: key, value: value, meta: { location: location(), options: options } };}, 
    peg$c69 = function peg$c69(first, key, value) {return { type: 'InterfaceCompositeElement', key: key, value: value, meta: { location: location(), options: options } };}, 
    peg$c70 = function peg$c70(first, content) {return content;}, 
    peg$c71 = "}", 
    peg$c72 = { type: "literal", value: "}", description: "\"}\"" }, 
    peg$c73 = function peg$c73(first, rest) {return { type: 'InterfaceComposite', element: mergeElements(first, rest), meta: { location: location(), options: options } };}, 
    peg$c74 = { type: "other", description: "the direction of a data flow" }, 
    peg$c75 = "out", 
    peg$c76 = { type: "literal", value: "out", description: "\"out\"" }, 
    peg$c77 = "in", 
    peg$c78 = { type: "literal", value: "in", description: "\"in\"" }, 
    peg$c79 = "ref", 
    peg$c80 = { type: "literal", value: "ref", description: "\"ref\"" }, 
    peg$c81 = "data", 
    peg$c82 = { type: "literal", value: "data", description: "\"data\"" }, 
    peg$c83 = function peg$c83(signature, definitions, data) {
      return { 
        type: 'DataDefinition', 
        data: data, 
        signature: signature, 
        definitions: definitions === null ? [] : definitions, 
        meta: { location: location(), options: options } };}, 


    peg$c84 = { type: "other", description: "the specification of a data type" }, 
    peg$c85 = { type: "other", description: "the specification of an data type using operators" }, 
    peg$c86 = function peg$c86(operator, first, rest) {return { type: "DataOperation", operator: operator, operand: mergeElements(first, rest), meta: { location: location(), options: options } };}, 
    peg$c87 = { type: "other", description: "an data type operator (union,intersection,complement)" }, 
    peg$c88 = { type: "other", description: "the specification of an atomic data type" }, 
    peg$c89 = function peg$c89(name) {return { type: 'DataAtomic', name: name, meta: { location: location(), options: options } };}, 
    peg$c90 = { type: "other", description: "the specification of a composite data type" }, 
    peg$c91 = function peg$c91(key, value) {return { type: 'DataCompositeElement', key: key, value: value, meta: { location: location(), options: options } };}, 
    peg$c92 = function peg$c92(first, key, value) {return { type: 'DataCompositeElement', key: key, value: value, meta: { location: location(), options: options } };}, 
    peg$c93 = function peg$c93(first, rest) {return { type: 'DataComposite', element: mergeElements(first, rest), meta: { location: location(), options: options } };}, 
    peg$c94 = { type: "other", description: "the specification of an array type" }, 
    peg$c95 = "[", 
    peg$c96 = { type: "literal", value: "[", description: "\"[\"" }, 
    peg$c97 = "]", 
    peg$c98 = { type: "literal", value: "]", description: "\"]\"" }, 
    peg$c99 = function peg$c99(element) {return { type: 'DataArray', element: element, meta: { location: location(), options: options } };}, 
    peg$c100 = { type: "other", description: "the specification of a function type" }, 
    peg$c101 = "→", 
    peg$c102 = { type: "literal", value: "→", description: "\"\\u2192\"" }, 
    peg$c103 = "->", 
    peg$c104 = { type: "literal", value: "->", description: "\"->\"" }, 
    peg$c105 = function peg$c105(domain, codomain) {return { type: 'DataFunction', domain: domain, codomain: codomain, meta: { location: location(), options: options } };}, 
    peg$c106 = { type: "other", description: "an operator identifier" }, 
    peg$c107 = /^[^()]/, 
    peg$c108 = { type: "class", value: "[^\\(\\)]", description: "[^\\(\\)]" }, 
    peg$c109 = function peg$c109(val) {return val.join('');}, 
    peg$c110 = { type: "other", description: "an interfac identifier" }, 
    peg$c111 = /^[A-Z]/, 
    peg$c112 = { type: "class", value: "[A-Z]", description: "[A-Z]" }, 
    peg$c113 = /^[a-zA-Z0-9]/, 
    peg$c114 = { type: "class", value: "[a-zA-Z0-9]", description: "[a-zA-Z0-9]" }, 
    peg$c115 = function peg$c115(first, rest) {return mergeElements(first, rest).join('');}, 
    peg$c116 = { type: "other", description: "a data identifier" }, 
    peg$c117 = { type: "other", description: "a variable identifier" }, 
    peg$c118 = /^[a-z]/, 
    peg$c119 = { type: "class", value: "[a-z]", description: "[a-z]" }, 
    peg$c120 = { type: "other", description: "a key identifier" }, 
    peg$c121 = /^[a-z0-9]/, 
    peg$c122 = { type: "class", value: "[a-z0-9]", description: "[a-z0-9]" }, 
    peg$c123 = { type: "other", description: "a C-compatible function identifier" }, 
    peg$c124 = /^[a-zA-Z_]/, 
    peg$c125 = { type: "class", value: "[a-zA-Z_]", description: "[a-zA-Z_]" }, 
    peg$c126 = /^[a-zA-Z0-9_]/, 
    peg$c127 = { type: "class", value: "[a-zA-Z0-9_]", description: "[a-zA-Z0-9_]" }, 
    peg$c128 = { type: "other", description: "white space" }, 
    peg$c129 = /^[ \t\r\n]/, 
    peg$c130 = { type: "class", value: "[ \\t\\r\\n]", description: "[ \\t\\r\\n]" }, 

    peg$currPos = 0, 
    peg$savedPos = 0, 
    peg$posDetailsCache = [{ line: 1, column: 1, seenCR: false }], 
    peg$maxFailPos = 0, 
    peg$maxFailExpected = [], 
    peg$silentFails = 0, 

    peg$result;

    if ("startRule" in options) {
      if (!(options.startRule in peg$startRuleFunctions)) {
        throw new Error("Can't start parsing from rule \"" + options.startRule + "\".");}


      peg$startRuleFunction = peg$startRuleFunctions[options.startRule];}


    function text() {
      return input.substring(peg$savedPos, peg$currPos);}


    function location() {
      return peg$computeLocation(peg$savedPos, peg$currPos);}


    function expected(description) {
      throw peg$buildException(
      null, 
      [{ type: "other", description: description }], 
      input.substring(peg$savedPos, peg$currPos), 
      peg$computeLocation(peg$savedPos, peg$currPos));}



    function error(message) {
      throw peg$buildException(
      message, 
      null, 
      input.substring(peg$savedPos, peg$currPos), 
      peg$computeLocation(peg$savedPos, peg$currPos));}



    function peg$computePosDetails(pos) {
      var details = peg$posDetailsCache[pos], 
      p, ch;

      if (details) {
        return details;} else 
      {
        p = pos - 1;
        while (!peg$posDetailsCache[p]) {
          p--;}


        details = peg$posDetailsCache[p];
        details = { 
          line: details.line, 
          column: details.column, 
          seenCR: details.seenCR };


        while (p < pos) {
          ch = input.charAt(p);
          if (ch === "\n") {
            if (!details.seenCR) {details.line++;}
            details.column = 1;
            details.seenCR = false;} else 
          if (ch === "\r" || ch === "\u2028" || ch === "\u2029") {
            details.line++;
            details.column = 1;
            details.seenCR = true;} else 
          {
            details.column++;
            details.seenCR = false;}


          p++;}


        peg$posDetailsCache[pos] = details;
        return details;}}



    function peg$computeLocation(startPos, endPos) {
      var startPosDetails = peg$computePosDetails(startPos), 
      endPosDetails = peg$computePosDetails(endPos);

      return { 
        start: { 
          offset: startPos, 
          line: startPosDetails.line, 
          column: startPosDetails.column }, 

        end: { 
          offset: endPos, 
          line: endPosDetails.line, 
          column: endPosDetails.column } };}




    function peg$fail(expected) {
      if (peg$currPos < peg$maxFailPos) {return;}

      if (peg$currPos > peg$maxFailPos) {
        peg$maxFailPos = peg$currPos;
        peg$maxFailExpected = [];}


      peg$maxFailExpected.push(expected);}


    function peg$buildException(message, expected, found, location) {
      function cleanupExpected(expected) {
        var i = 1;

        expected.sort(function (a, b) {
          if (a.description < b.description) {
            return -1;} else 
          if (a.description > b.description) {
            return 1;} else 
          {
            return 0;}});



        while (i < expected.length) {
          if (expected[i - 1] === expected[i]) {
            expected.splice(i, 1);} else 
          {
            i++;}}}




      function buildMessage(expected, found) {
        function stringEscape(s) {
          function hex(ch) {return ch.charCodeAt(0).toString(16).toUpperCase();}

          return s.
          replace(/\\/g, '\\\\').
          replace(/"/g, '\\"').
          replace(/\x08/g, '\\b').
          replace(/\t/g, '\\t').
          replace(/\n/g, '\\n').
          replace(/\f/g, '\\f').
          replace(/\r/g, '\\r').
          replace(/[\x00-\x07\x0B\x0E\x0F]/g, function (ch) {return '\\x0' + hex(ch);}).
          replace(/[\x10-\x1F\x80-\xFF]/g, function (ch) {return '\\x' + hex(ch);}).
          replace(/[\u0100-\u0FFF]/g, function (ch) {return "\\u0" + hex(ch);}).
          replace(/[\u1000-\uFFFF]/g, function (ch) {return "\\u" + hex(ch);});}


        var expectedDescs = new Array(expected.length), 
        expectedDesc, foundDesc, i;

        for (i = 0; i < expected.length; i++) {
          expectedDescs[i] = expected[i].description;}


        expectedDesc = expected.length > 1 ? 
        expectedDescs.slice(0, -1).join(", ") + 
        " or " + 
        expectedDescs[expected.length - 1] : 
        expectedDescs[0];

        foundDesc = found ? "\"" + stringEscape(found) + "\"" : "end of input";

        return "Expected " + expectedDesc + " but " + foundDesc + " found.";}


      if (expected !== null) {
        cleanupExpected(expected);}


      return new peg$SyntaxError(
      message !== null ? message : buildMessage(expected, found), 
      expected, 
      found, 
      location);}



    function peg$parsestart() {
      var s0, s1, s2, s3;

      s0 = peg$currPos;
      s1 = peg$parse_();
      if (s1 !== peg$FAILED) {
        s2 = peg$parsedefinitions();
        if (s2 !== peg$FAILED) {
          s3 = peg$parse_();
          if (s3 !== peg$FAILED) {
            peg$savedPos = s0;
            s1 = peg$c0(s2);
            s0 = s1;} else 
          {
            peg$currPos = s0;
            s0 = peg$FAILED;}} else 

        {
          peg$currPos = s0;
          s0 = peg$FAILED;}} else 

      {
        peg$currPos = s0;
        s0 = peg$FAILED;}


      return s0;}


    function peg$parsedefinitions() {
      var s0, s1, s2, s3;

      peg$silentFails++;
      s0 = peg$currPos;
      s1 = peg$parse_();
      if (s1 !== peg$FAILED) {
        s2 = [];
        s3 = peg$parsecontent();
        while (s3 !== peg$FAILED) {
          s2.push(s3);
          s3 = peg$parsecontent();}

        if (s2 !== peg$FAILED) {
          s3 = peg$parse_();
          if (s3 !== peg$FAILED) {
            peg$savedPos = s0;
            s1 = peg$c2(s2);
            s0 = s1;} else 
          {
            peg$currPos = s0;
            s0 = peg$FAILED;}} else 

        {
          peg$currPos = s0;
          s0 = peg$FAILED;}} else 

      {
        peg$currPos = s0;
        s0 = peg$FAILED;}

      peg$silentFails--;
      if (s0 === peg$FAILED) {
        s1 = peg$FAILED;
        if (peg$silentFails === 0) {peg$fail(peg$c1);}}


      return s0;}


    function peg$parsecontent() {
      var s0, s1, s2, s3, s4, s5;

      peg$silentFails++;
      s0 = peg$currPos;
      s1 = peg$parse_();
      if (s1 !== peg$FAILED) {
        s2 = peg$parseinteractionDefinition();
        if (s2 !== peg$FAILED) {
          peg$savedPos = s0;
          s1 = peg$c4(s2);
          s0 = s1;} else 
        {
          peg$currPos = s0;
          s0 = peg$FAILED;}} else 

      {
        peg$currPos = s0;
        s0 = peg$FAILED;}

      if (s0 === peg$FAILED) {
        s0 = peg$currPos;
        s1 = peg$parse_();
        if (s1 !== peg$FAILED) {
          s2 = peg$parseinterfaceDefinition();
          if (s2 !== peg$FAILED) {
            peg$savedPos = s0;
            s1 = peg$c5(s2);
            s0 = s1;} else 
          {
            peg$currPos = s0;
            s0 = peg$FAILED;}} else 

        {
          peg$currPos = s0;
          s0 = peg$FAILED;}

        if (s0 === peg$FAILED) {
          s0 = peg$currPos;
          s1 = peg$parse_();
          if (s1 !== peg$FAILED) {
            s2 = peg$parsedataDefinition();
            if (s2 !== peg$FAILED) {
              peg$savedPos = s0;
              s1 = peg$c6(s2);
              s0 = s1;} else 
            {
              peg$currPos = s0;
              s0 = peg$FAILED;}} else 

          {
            peg$currPos = s0;
            s0 = peg$FAILED;}

          if (s0 === peg$FAILED) {
            s0 = peg$currPos;
            s1 = peg$parse_();
            if (s1 !== peg$FAILED) {
              if (input.substr(peg$currPos, 6) === peg$c7) {
                s2 = peg$c7;
                peg$currPos += 6;} else 
              {
                s2 = peg$FAILED;
                if (peg$silentFails === 0) {peg$fail(peg$c8);}}

              if (s2 !== peg$FAILED) {
                s3 = peg$parse_();
                if (s3 !== peg$FAILED) {
                  s4 = [];
                  if (peg$c9.test(input.charAt(peg$currPos))) {
                    s5 = input.charAt(peg$currPos);
                    peg$currPos++;} else 
                  {
                    s5 = peg$FAILED;
                    if (peg$silentFails === 0) {peg$fail(peg$c10);}}

                  while (s5 !== peg$FAILED) {
                    s4.push(s5);
                    if (peg$c9.test(input.charAt(peg$currPos))) {
                      s5 = input.charAt(peg$currPos);
                      peg$currPos++;} else 
                    {
                      s5 = peg$FAILED;
                      if (peg$silentFails === 0) {peg$fail(peg$c10);}}}


                  if (s4 !== peg$FAILED) {
                    s5 = peg$parse_();
                    if (s5 !== peg$FAILED) {
                      peg$savedPos = s0;
                      s1 = peg$c11(s4);
                      s0 = s1;} else 
                    {
                      peg$currPos = s0;
                      s0 = peg$FAILED;}} else 

                  {
                    peg$currPos = s0;
                    s0 = peg$FAILED;}} else 

                {
                  peg$currPos = s0;
                  s0 = peg$FAILED;}} else 

              {
                peg$currPos = s0;
                s0 = peg$FAILED;}} else 

            {
              peg$currPos = s0;
              s0 = peg$FAILED;}}}}




      peg$silentFails--;
      if (s0 === peg$FAILED) {
        s1 = peg$FAILED;
        if (peg$silentFails === 0) {peg$fail(peg$c3);}}


      return s0;}


    function peg$parseinteractionDefinition() {
      var s0, s1, s2, s3, s4, s5, s6, s7, s8, s9, s10, s11;

      peg$silentFails++;
      s0 = peg$currPos;
      s1 = peg$parse_();
      if (s1 !== peg$FAILED) {
        if (input.substr(peg$currPos, 11) === peg$c13) {
          s2 = peg$c13;
          peg$currPos += 11;} else 
        {
          s2 = peg$FAILED;
          if (peg$silentFails === 0) {peg$fail(peg$c14);}}

        if (s2 !== peg$FAILED) {
          s3 = peg$parse_();
          if (s3 !== peg$FAILED) {
            s4 = peg$parseinteractionSignature();
            if (s4 !== peg$FAILED) {
              s5 = peg$parse_();
              if (s5 !== peg$FAILED) {
                s6 = peg$currPos;
                s7 = peg$parse_();
                if (s7 !== peg$FAILED) {
                  if (input.substr(peg$currPos, 4) === peg$c15) {
                    s8 = peg$c15;
                    peg$currPos += 4;} else 
                  {
                    s8 = peg$FAILED;
                    if (peg$silentFails === 0) {peg$fail(peg$c16);}}

                  if (s8 !== peg$FAILED) {
                    s9 = peg$parse_();
                    if (s9 !== peg$FAILED) {
                      s10 = peg$parsedefinitions();
                      if (s10 !== peg$FAILED) {
                        peg$savedPos = s6;
                        s7 = peg$c17(s4, s10);
                        s6 = s7;} else 
                      {
                        peg$currPos = s6;
                        s6 = peg$FAILED;}} else 

                    {
                      peg$currPos = s6;
                      s6 = peg$FAILED;}} else 

                  {
                    peg$currPos = s6;
                    s6 = peg$FAILED;}} else 

                {
                  peg$currPos = s6;
                  s6 = peg$FAILED;}

                if (s6 === peg$FAILED) {
                  s6 = null;}

                if (s6 !== peg$FAILED) {
                  s7 = peg$parse_();
                  if (s7 !== peg$FAILED) {
                    if (input.substr(peg$currPos, 2) === peg$c18) {
                      s8 = peg$c18;
                      peg$currPos += 2;} else 
                    {
                      s8 = peg$FAILED;
                      if (peg$silentFails === 0) {peg$fail(peg$c19);}}

                    if (s8 !== peg$FAILED) {
                      s9 = peg$parse_();
                      if (s9 !== peg$FAILED) {
                        s10 = peg$parseinteraction();
                        if (s10 !== peg$FAILED) {
                          s11 = peg$parse_();
                          if (s11 !== peg$FAILED) {
                            peg$savedPos = s0;
                            s1 = peg$c20(s4, s6, s10);
                            s0 = s1;} else 
                          {
                            peg$currPos = s0;
                            s0 = peg$FAILED;}} else 

                        {
                          peg$currPos = s0;
                          s0 = peg$FAILED;}} else 

                      {
                        peg$currPos = s0;
                        s0 = peg$FAILED;}} else 

                    {
                      peg$currPos = s0;
                      s0 = peg$FAILED;}} else 

                  {
                    peg$currPos = s0;
                    s0 = peg$FAILED;}} else 

                {
                  peg$currPos = s0;
                  s0 = peg$FAILED;}} else 

              {
                peg$currPos = s0;
                s0 = peg$FAILED;}} else 

            {
              peg$currPos = s0;
              s0 = peg$FAILED;}} else 

          {
            peg$currPos = s0;
            s0 = peg$FAILED;}} else 

        {
          peg$currPos = s0;
          s0 = peg$FAILED;}} else 

      {
        peg$currPos = s0;
        s0 = peg$FAILED;}

      peg$silentFails--;
      if (s0 === peg$FAILED) {
        s1 = peg$FAILED;
        if (peg$silentFails === 0) {peg$fail(peg$c12);}}


      return s0;}


    function peg$parseinteractionSignature() {
      var s0, s1, s2, s3, s4, s5, s6, s7;

      peg$silentFails++;
      s0 = peg$currPos;
      if (input.charCodeAt(peg$currPos) === 40) {
        s1 = peg$c22;
        peg$currPos++;} else 
      {
        s1 = peg$FAILED;
        if (peg$silentFails === 0) {peg$fail(peg$c23);}}

      if (s1 !== peg$FAILED) {
        s2 = [];
        s3 = peg$parseinteractionSignatureElement();
        while (s3 !== peg$FAILED) {
          s2.push(s3);
          s3 = peg$parseinteractionSignatureElement();}

        if (s2 !== peg$FAILED) {
          if (input.charCodeAt(peg$currPos) === 41) {
            s3 = peg$c24;
            peg$currPos++;} else 
          {
            s3 = peg$FAILED;
            if (peg$silentFails === 0) {peg$fail(peg$c25);}}

          if (s3 !== peg$FAILED) {
            s4 = peg$parse_();
            if (s4 !== peg$FAILED) {
              if (input.charCodeAt(peg$currPos) === 58) {
                s5 = peg$c26;
                peg$currPos++;} else 
              {
                s5 = peg$FAILED;
                if (peg$silentFails === 0) {peg$fail(peg$c27);}}

              if (s5 !== peg$FAILED) {
                s6 = peg$parse_();
                if (s6 !== peg$FAILED) {
                  s7 = peg$parseinterfac();
                  if (s7 !== peg$FAILED) {
                    peg$savedPos = s0;
                    s1 = peg$c28(s2, s7);
                    s0 = s1;} else 
                  {
                    peg$currPos = s0;
                    s0 = peg$FAILED;}} else 

                {
                  peg$currPos = s0;
                  s0 = peg$FAILED;}} else 

              {
                peg$currPos = s0;
                s0 = peg$FAILED;}} else 

            {
              peg$currPos = s0;
              s0 = peg$FAILED;}} else 

          {
            peg$currPos = s0;
            s0 = peg$FAILED;}} else 

        {
          peg$currPos = s0;
          s0 = peg$FAILED;}} else 

      {
        peg$currPos = s0;
        s0 = peg$FAILED;}

      peg$silentFails--;
      if (s0 === peg$FAILED) {
        s1 = peg$FAILED;
        if (peg$silentFails === 0) {peg$fail(peg$c21);}}


      return s0;}


    function peg$parseinteractionSignatureElement() {
      var s0, s1, s2, s3, s4, s5, s6, s7, s8, s9;

      peg$silentFails++;
      s0 = peg$currPos;
      s1 = peg$parseoperatorIdentifier();
      if (s1 !== peg$FAILED) {
        peg$savedPos = s0;
        s1 = peg$c30(s1);}

      s0 = s1;
      if (s0 === peg$FAILED) {
        s0 = peg$currPos;
        if (input.charCodeAt(peg$currPos) === 40) {
          s1 = peg$c22;
          peg$currPos++;} else 
        {
          s1 = peg$FAILED;
          if (peg$silentFails === 0) {peg$fail(peg$c23);}}

        if (s1 !== peg$FAILED) {
          s2 = peg$parse_();
          if (s2 !== peg$FAILED) {
            s3 = peg$parsevariableIdentifier();
            if (s3 !== peg$FAILED) {
              s4 = peg$parse_();
              if (s4 !== peg$FAILED) {
                if (input.charCodeAt(peg$currPos) === 58) {
                  s5 = peg$c26;
                  peg$currPos++;} else 
                {
                  s5 = peg$FAILED;
                  if (peg$silentFails === 0) {peg$fail(peg$c27);}}

                if (s5 !== peg$FAILED) {
                  s6 = peg$parse_();
                  if (s6 !== peg$FAILED) {
                    s7 = peg$parseinterfac();
                    if (s7 !== peg$FAILED) {
                      s8 = peg$parse_();
                      if (s8 !== peg$FAILED) {
                        if (input.charCodeAt(peg$currPos) === 41) {
                          s9 = peg$c24;
                          peg$currPos++;} else 
                        {
                          s9 = peg$FAILED;
                          if (peg$silentFails === 0) {peg$fail(peg$c25);}}

                        if (s9 !== peg$FAILED) {
                          peg$savedPos = s0;
                          s1 = peg$c31(s3, s7);
                          s0 = s1;} else 
                        {
                          peg$currPos = s0;
                          s0 = peg$FAILED;}} else 

                      {
                        peg$currPos = s0;
                        s0 = peg$FAILED;}} else 

                    {
                      peg$currPos = s0;
                      s0 = peg$FAILED;}} else 

                  {
                    peg$currPos = s0;
                    s0 = peg$FAILED;}} else 

                {
                  peg$currPos = s0;
                  s0 = peg$FAILED;}} else 

              {
                peg$currPos = s0;
                s0 = peg$FAILED;}} else 

            {
              peg$currPos = s0;
              s0 = peg$FAILED;}} else 

          {
            peg$currPos = s0;
            s0 = peg$FAILED;}} else 

        {
          peg$currPos = s0;
          s0 = peg$FAILED;}}


      peg$silentFails--;
      if (s0 === peg$FAILED) {
        s1 = peg$FAILED;
        if (peg$silentFails === 0) {peg$fail(peg$c29);}}


      return s0;}


    function peg$parseinteraction() {
      var s0, s1, s2, s3, s4;

      peg$silentFails++;
      s0 = peg$currPos;
      if (input.charCodeAt(peg$currPos) === 40) {
        s1 = peg$c22;
        peg$currPos++;} else 
      {
        s1 = peg$FAILED;
        if (peg$silentFails === 0) {peg$fail(peg$c23);}}

      if (s1 !== peg$FAILED) {
        s2 = [];
        s3 = peg$parseinteractionElement();
        while (s3 !== peg$FAILED) {
          s2.push(s3);
          s3 = peg$parseinteractionElement();}

        if (s2 !== peg$FAILED) {
          s3 = peg$parse_();
          if (s3 !== peg$FAILED) {
            if (input.charCodeAt(peg$currPos) === 41) {
              s4 = peg$c24;
              peg$currPos++;} else 
            {
              s4 = peg$FAILED;
              if (peg$silentFails === 0) {peg$fail(peg$c25);}}

            if (s4 !== peg$FAILED) {
              peg$savedPos = s0;
              s1 = peg$c33(s2);
              s0 = s1;} else 
            {
              peg$currPos = s0;
              s0 = peg$FAILED;}} else 

          {
            peg$currPos = s0;
            s0 = peg$FAILED;}} else 

        {
          peg$currPos = s0;
          s0 = peg$FAILED;}} else 

      {
        peg$currPos = s0;
        s0 = peg$FAILED;}

      peg$silentFails--;
      if (s0 === peg$FAILED) {
        s1 = peg$FAILED;
        if (peg$silentFails === 0) {peg$fail(peg$c32);}}


      return s0;}


    function peg$parseinteractionElement() {
      var s0, s1;

      peg$silentFails++;
      s0 = peg$currPos;
      s1 = peg$parseinteraction();
      if (s1 !== peg$FAILED) {
        peg$savedPos = s0;
        s1 = peg$c35(s1);}

      s0 = s1;
      if (s0 === peg$FAILED) {
        s0 = peg$currPos;
        s1 = peg$parseoperatorIdentifier();
        if (s1 !== peg$FAILED) {
          peg$savedPos = s0;
          s1 = peg$c30(s1);}

        s0 = s1;}

      peg$silentFails--;
      if (s0 === peg$FAILED) {
        s1 = peg$FAILED;
        if (peg$silentFails === 0) {peg$fail(peg$c34);}}


      return s0;}


    function peg$parseinterfaceDefinition() {
      var s0, s1, s2, s3, s4, s5, s6, s7, s8, s9, s10, s11;

      peg$silentFails++;
      s0 = peg$currPos;
      s1 = peg$parse_();
      if (s1 !== peg$FAILED) {
        if (input.substr(peg$currPos, 9) === peg$c37) {
          s2 = peg$c37;
          peg$currPos += 9;} else 
        {
          s2 = peg$FAILED;
          if (peg$silentFails === 0) {peg$fail(peg$c38);}}

        if (s2 !== peg$FAILED) {
          s3 = peg$parse_();
          if (s3 !== peg$FAILED) {
            s4 = peg$parseinterfaceIdentifier();
            if (s4 !== peg$FAILED) {
              s5 = peg$parse_();
              if (s5 !== peg$FAILED) {
                s6 = peg$currPos;
                s7 = peg$parse_();
                if (s7 !== peg$FAILED) {
                  if (input.substr(peg$currPos, 4) === peg$c15) {
                    s8 = peg$c15;
                    peg$currPos += 4;} else 
                  {
                    s8 = peg$FAILED;
                    if (peg$silentFails === 0) {peg$fail(peg$c16);}}

                  if (s8 !== peg$FAILED) {
                    s9 = peg$parse_();
                    if (s9 !== peg$FAILED) {
                      s10 = peg$parsedefinitions();
                      if (s10 !== peg$FAILED) {
                        peg$savedPos = s6;
                        s7 = peg$c17(s4, s10);
                        s6 = s7;} else 
                      {
                        peg$currPos = s6;
                        s6 = peg$FAILED;}} else 

                    {
                      peg$currPos = s6;
                      s6 = peg$FAILED;}} else 

                  {
                    peg$currPos = s6;
                    s6 = peg$FAILED;}} else 

                {
                  peg$currPos = s6;
                  s6 = peg$FAILED;}

                if (s6 === peg$FAILED) {
                  s6 = null;}

                if (s6 !== peg$FAILED) {
                  s7 = peg$parse_();
                  if (s7 !== peg$FAILED) {
                    if (input.substr(peg$currPos, 2) === peg$c18) {
                      s8 = peg$c18;
                      peg$currPos += 2;} else 
                    {
                      s8 = peg$FAILED;
                      if (peg$silentFails === 0) {peg$fail(peg$c19);}}

                    if (s8 !== peg$FAILED) {
                      s9 = peg$parse_();
                      if (s9 !== peg$FAILED) {
                        s10 = peg$parseinterfac();
                        if (s10 !== peg$FAILED) {
                          s11 = peg$parse_();
                          if (s11 !== peg$FAILED) {
                            peg$savedPos = s0;
                            s1 = peg$c39(s4, s6, s10);
                            s0 = s1;} else 
                          {
                            peg$currPos = s0;
                            s0 = peg$FAILED;}} else 

                        {
                          peg$currPos = s0;
                          s0 = peg$FAILED;}} else 

                      {
                        peg$currPos = s0;
                        s0 = peg$FAILED;}} else 

                    {
                      peg$currPos = s0;
                      s0 = peg$FAILED;}} else 

                  {
                    peg$currPos = s0;
                    s0 = peg$FAILED;}} else 

                {
                  peg$currPos = s0;
                  s0 = peg$FAILED;}} else 

              {
                peg$currPos = s0;
                s0 = peg$FAILED;}} else 

            {
              peg$currPos = s0;
              s0 = peg$FAILED;}} else 

          {
            peg$currPos = s0;
            s0 = peg$FAILED;}} else 

        {
          peg$currPos = s0;
          s0 = peg$FAILED;}} else 

      {
        peg$currPos = s0;
        s0 = peg$FAILED;}

      peg$silentFails--;
      if (s0 === peg$FAILED) {
        s1 = peg$FAILED;
        if (peg$silentFails === 0) {peg$fail(peg$c36);}}


      return s0;}


    function peg$parseinterfac() {
      var s0, s1;

      peg$silentFails++;
      s0 = peg$parseinterfaceAtomic();
      if (s0 === peg$FAILED) {
        s0 = peg$parseinterfaceComposite();
        if (s0 === peg$FAILED) {
          s0 = peg$parseinterfaceOperation();}}


      peg$silentFails--;
      if (s0 === peg$FAILED) {
        s1 = peg$FAILED;
        if (peg$silentFails === 0) {peg$fail(peg$c40);}}


      return s0;}


    function peg$parseinterfaceOperation() {
      var s0, s1, s2, s3, s4, s5, s6, s7, s8, s9, s10, s11;

      peg$silentFails++;
      s0 = peg$currPos;
      s1 = peg$parseinterfaceOperator();
      if (s1 !== peg$FAILED) {
        s2 = peg$parse_();
        if (s2 !== peg$FAILED) {
          if (input.charCodeAt(peg$currPos) === 40) {
            s3 = peg$c22;
            peg$currPos++;} else 
          {
            s3 = peg$FAILED;
            if (peg$silentFails === 0) {peg$fail(peg$c23);}}

          if (s3 !== peg$FAILED) {
            s4 = peg$parse_();
            if (s4 !== peg$FAILED) {
              s5 = peg$parseinterfac();
              if (s5 !== peg$FAILED) {
                s6 = [];
                s7 = peg$currPos;
                s8 = peg$parse_();
                if (s8 !== peg$FAILED) {
                  if (input.charCodeAt(peg$currPos) === 44) {
                    s9 = peg$c42;
                    peg$currPos++;} else 
                  {
                    s9 = peg$FAILED;
                    if (peg$silentFails === 0) {peg$fail(peg$c43);}}

                  if (s9 !== peg$FAILED) {
                    s10 = peg$parse_();
                    if (s10 !== peg$FAILED) {
                      s11 = peg$parseinterfac();
                      if (s11 !== peg$FAILED) {
                        peg$savedPos = s7;
                        s8 = peg$c44(s1, s5, s11);
                        s7 = s8;} else 
                      {
                        peg$currPos = s7;
                        s7 = peg$FAILED;}} else 

                    {
                      peg$currPos = s7;
                      s7 = peg$FAILED;}} else 

                  {
                    peg$currPos = s7;
                    s7 = peg$FAILED;}} else 

                {
                  peg$currPos = s7;
                  s7 = peg$FAILED;}

                while (s7 !== peg$FAILED) {
                  s6.push(s7);
                  s7 = peg$currPos;
                  s8 = peg$parse_();
                  if (s8 !== peg$FAILED) {
                    if (input.charCodeAt(peg$currPos) === 44) {
                      s9 = peg$c42;
                      peg$currPos++;} else 
                    {
                      s9 = peg$FAILED;
                      if (peg$silentFails === 0) {peg$fail(peg$c43);}}

                    if (s9 !== peg$FAILED) {
                      s10 = peg$parse_();
                      if (s10 !== peg$FAILED) {
                        s11 = peg$parseinterfac();
                        if (s11 !== peg$FAILED) {
                          peg$savedPos = s7;
                          s8 = peg$c44(s1, s5, s11);
                          s7 = s8;} else 
                        {
                          peg$currPos = s7;
                          s7 = peg$FAILED;}} else 

                      {
                        peg$currPos = s7;
                        s7 = peg$FAILED;}} else 

                    {
                      peg$currPos = s7;
                      s7 = peg$FAILED;}} else 

                  {
                    peg$currPos = s7;
                    s7 = peg$FAILED;}}


                if (s6 !== peg$FAILED) {
                  s7 = peg$parse_();
                  if (s7 !== peg$FAILED) {
                    if (input.charCodeAt(peg$currPos) === 41) {
                      s8 = peg$c24;
                      peg$currPos++;} else 
                    {
                      s8 = peg$FAILED;
                      if (peg$silentFails === 0) {peg$fail(peg$c25);}}

                    if (s8 !== peg$FAILED) {
                      peg$savedPos = s0;
                      s1 = peg$c45(s1, s5, s6);
                      s0 = s1;} else 
                    {
                      peg$currPos = s0;
                      s0 = peg$FAILED;}} else 

                  {
                    peg$currPos = s0;
                    s0 = peg$FAILED;}} else 

                {
                  peg$currPos = s0;
                  s0 = peg$FAILED;}} else 

              {
                peg$currPos = s0;
                s0 = peg$FAILED;}} else 

            {
              peg$currPos = s0;
              s0 = peg$FAILED;}} else 

          {
            peg$currPos = s0;
            s0 = peg$FAILED;}} else 

        {
          peg$currPos = s0;
          s0 = peg$FAILED;}} else 

      {
        peg$currPos = s0;
        s0 = peg$FAILED;}

      peg$silentFails--;
      if (s0 === peg$FAILED) {
        s1 = peg$FAILED;
        if (peg$silentFails === 0) {peg$fail(peg$c41);}}


      return s0;}


    function peg$parseinterfaceOperator() {
      var s0, s1;

      peg$silentFails++;
      if (input.substr(peg$currPos, 11) === peg$c47) {
        s0 = peg$c47;
        peg$currPos += 11;} else 
      {
        s0 = peg$FAILED;
        if (peg$silentFails === 0) {peg$fail(peg$c48);}}

      if (s0 === peg$FAILED) {
        if (input.substr(peg$currPos, 13) === peg$c49) {
          s0 = peg$c49;
          peg$currPos += 13;} else 
        {
          s0 = peg$FAILED;
          if (peg$silentFails === 0) {peg$fail(peg$c50);}}

        if (s0 === peg$FAILED) {
          if (input.substr(peg$currPos, 12) === peg$c51) {
            s0 = peg$c51;
            peg$currPos += 12;} else 
          {
            s0 = peg$FAILED;
            if (peg$silentFails === 0) {peg$fail(peg$c52);}}

          if (s0 === peg$FAILED) {
            if (input.substr(peg$currPos, 9) === peg$c53) {
              s0 = peg$c53;
              peg$currPos += 9;} else 
            {
              s0 = peg$FAILED;
              if (peg$silentFails === 0) {peg$fail(peg$c54);}}

            if (s0 === peg$FAILED) {
              if (input.substr(peg$currPos, 8) === peg$c55) {
                s0 = peg$c55;
                peg$currPos += 8;} else 
              {
                s0 = peg$FAILED;
                if (peg$silentFails === 0) {peg$fail(peg$c56);}}

              if (s0 === peg$FAILED) {
                if (input.substr(peg$currPos, 5) === peg$c57) {
                  s0 = peg$c57;
                  peg$currPos += 5;} else 
                {
                  s0 = peg$FAILED;
                  if (peg$silentFails === 0) {peg$fail(peg$c58);}}

                if (s0 === peg$FAILED) {
                  if (input.substr(peg$currPos, 12) === peg$c59) {
                    s0 = peg$c59;
                    peg$currPos += 12;} else 
                  {
                    s0 = peg$FAILED;
                    if (peg$silentFails === 0) {peg$fail(peg$c60);}}

                  if (s0 === peg$FAILED) {
                    if (input.substr(peg$currPos, 10) === peg$c61) {
                      s0 = peg$c61;
                      peg$currPos += 10;} else 
                    {
                      s0 = peg$FAILED;
                      if (peg$silentFails === 0) {peg$fail(peg$c62);}}}}}}}}}








      peg$silentFails--;
      if (s0 === peg$FAILED) {
        s1 = peg$FAILED;
        if (peg$silentFails === 0) {peg$fail(peg$c46);}}


      return s0;}


    function peg$parseinterfaceAtomic() {
      var s0, s1, s2, s3;

      peg$silentFails++;
      s0 = peg$currPos;
      s1 = peg$parsedata();
      if (s1 !== peg$FAILED) {
        s2 = peg$parse_();
        if (s2 !== peg$FAILED) {
          s3 = peg$parsedirection();
          if (s3 !== peg$FAILED) {
            peg$savedPos = s0;
            s1 = peg$c64(s1, s3);
            s0 = s1;} else 
          {
            peg$currPos = s0;
            s0 = peg$FAILED;}} else 

        {
          peg$currPos = s0;
          s0 = peg$FAILED;}} else 

      {
        peg$currPos = s0;
        s0 = peg$FAILED;}

      peg$silentFails--;
      if (s0 === peg$FAILED) {
        s1 = peg$FAILED;
        if (peg$silentFails === 0) {peg$fail(peg$c63);}}


      return s0;}


    function peg$parseinterfaceComposite() {
      var s0, s1, s2, s3, s4, s5, s6, s7, s8, s9, s10, s11, s12, s13, s14;

      peg$silentFails++;
      s0 = peg$currPos;
      if (input.charCodeAt(peg$currPos) === 123) {
        s1 = peg$c66;
        peg$currPos++;} else 
      {
        s1 = peg$FAILED;
        if (peg$silentFails === 0) {peg$fail(peg$c67);}}

      if (s1 !== peg$FAILED) {
        s2 = peg$parse_();
        if (s2 !== peg$FAILED) {
          s3 = peg$currPos;
          s4 = peg$parsekeyIdentifier();
          if (s4 !== peg$FAILED) {
            s5 = peg$parse_();
            if (s5 !== peg$FAILED) {
              if (input.charCodeAt(peg$currPos) === 58) {
                s6 = peg$c26;
                peg$currPos++;} else 
              {
                s6 = peg$FAILED;
                if (peg$silentFails === 0) {peg$fail(peg$c27);}}

              if (s6 !== peg$FAILED) {
                s7 = peg$parse_();
                if (s7 !== peg$FAILED) {
                  s8 = peg$parseinterfac();
                  if (s8 !== peg$FAILED) {
                    peg$savedPos = s3;
                    s4 = peg$c68(s4, s8);
                    s3 = s4;} else 
                  {
                    peg$currPos = s3;
                    s3 = peg$FAILED;}} else 

                {
                  peg$currPos = s3;
                  s3 = peg$FAILED;}} else 

              {
                peg$currPos = s3;
                s3 = peg$FAILED;}} else 

            {
              peg$currPos = s3;
              s3 = peg$FAILED;}} else 

          {
            peg$currPos = s3;
            s3 = peg$FAILED;}

          if (s3 !== peg$FAILED) {
            s4 = peg$parse_();
            if (s4 !== peg$FAILED) {
              s5 = [];
              s6 = peg$currPos;
              if (input.charCodeAt(peg$currPos) === 44) {
                s7 = peg$c42;
                peg$currPos++;} else 
              {
                s7 = peg$FAILED;
                if (peg$silentFails === 0) {peg$fail(peg$c43);}}

              if (s7 !== peg$FAILED) {
                s8 = peg$parse_();
                if (s8 !== peg$FAILED) {
                  s9 = peg$currPos;
                  s10 = peg$parsekeyIdentifier();
                  if (s10 !== peg$FAILED) {
                    s11 = peg$parse_();
                    if (s11 !== peg$FAILED) {
                      if (input.charCodeAt(peg$currPos) === 58) {
                        s12 = peg$c26;
                        peg$currPos++;} else 
                      {
                        s12 = peg$FAILED;
                        if (peg$silentFails === 0) {peg$fail(peg$c27);}}

                      if (s12 !== peg$FAILED) {
                        s13 = peg$parse_();
                        if (s13 !== peg$FAILED) {
                          s14 = peg$parseinterfac();
                          if (s14 !== peg$FAILED) {
                            peg$savedPos = s9;
                            s10 = peg$c69(s3, s10, s14);
                            s9 = s10;} else 
                          {
                            peg$currPos = s9;
                            s9 = peg$FAILED;}} else 

                        {
                          peg$currPos = s9;
                          s9 = peg$FAILED;}} else 

                      {
                        peg$currPos = s9;
                        s9 = peg$FAILED;}} else 

                    {
                      peg$currPos = s9;
                      s9 = peg$FAILED;}} else 

                  {
                    peg$currPos = s9;
                    s9 = peg$FAILED;}

                  if (s9 !== peg$FAILED) {
                    s10 = peg$parse_();
                    if (s10 !== peg$FAILED) {
                      peg$savedPos = s6;
                      s7 = peg$c70(s3, s9);
                      s6 = s7;} else 
                    {
                      peg$currPos = s6;
                      s6 = peg$FAILED;}} else 

                  {
                    peg$currPos = s6;
                    s6 = peg$FAILED;}} else 

                {
                  peg$currPos = s6;
                  s6 = peg$FAILED;}} else 

              {
                peg$currPos = s6;
                s6 = peg$FAILED;}

              while (s6 !== peg$FAILED) {
                s5.push(s6);
                s6 = peg$currPos;
                if (input.charCodeAt(peg$currPos) === 44) {
                  s7 = peg$c42;
                  peg$currPos++;} else 
                {
                  s7 = peg$FAILED;
                  if (peg$silentFails === 0) {peg$fail(peg$c43);}}

                if (s7 !== peg$FAILED) {
                  s8 = peg$parse_();
                  if (s8 !== peg$FAILED) {
                    s9 = peg$currPos;
                    s10 = peg$parsekeyIdentifier();
                    if (s10 !== peg$FAILED) {
                      s11 = peg$parse_();
                      if (s11 !== peg$FAILED) {
                        if (input.charCodeAt(peg$currPos) === 58) {
                          s12 = peg$c26;
                          peg$currPos++;} else 
                        {
                          s12 = peg$FAILED;
                          if (peg$silentFails === 0) {peg$fail(peg$c27);}}

                        if (s12 !== peg$FAILED) {
                          s13 = peg$parse_();
                          if (s13 !== peg$FAILED) {
                            s14 = peg$parseinterfac();
                            if (s14 !== peg$FAILED) {
                              peg$savedPos = s9;
                              s10 = peg$c69(s3, s10, s14);
                              s9 = s10;} else 
                            {
                              peg$currPos = s9;
                              s9 = peg$FAILED;}} else 

                          {
                            peg$currPos = s9;
                            s9 = peg$FAILED;}} else 

                        {
                          peg$currPos = s9;
                          s9 = peg$FAILED;}} else 

                      {
                        peg$currPos = s9;
                        s9 = peg$FAILED;}} else 

                    {
                      peg$currPos = s9;
                      s9 = peg$FAILED;}

                    if (s9 !== peg$FAILED) {
                      s10 = peg$parse_();
                      if (s10 !== peg$FAILED) {
                        peg$savedPos = s6;
                        s7 = peg$c70(s3, s9);
                        s6 = s7;} else 
                      {
                        peg$currPos = s6;
                        s6 = peg$FAILED;}} else 

                    {
                      peg$currPos = s6;
                      s6 = peg$FAILED;}} else 

                  {
                    peg$currPos = s6;
                    s6 = peg$FAILED;}} else 

                {
                  peg$currPos = s6;
                  s6 = peg$FAILED;}}


              if (s5 !== peg$FAILED) {
                if (input.charCodeAt(peg$currPos) === 125) {
                  s6 = peg$c71;
                  peg$currPos++;} else 
                {
                  s6 = peg$FAILED;
                  if (peg$silentFails === 0) {peg$fail(peg$c72);}}

                if (s6 !== peg$FAILED) {
                  peg$savedPos = s0;
                  s1 = peg$c73(s3, s5);
                  s0 = s1;} else 
                {
                  peg$currPos = s0;
                  s0 = peg$FAILED;}} else 

              {
                peg$currPos = s0;
                s0 = peg$FAILED;}} else 

            {
              peg$currPos = s0;
              s0 = peg$FAILED;}} else 

          {
            peg$currPos = s0;
            s0 = peg$FAILED;}} else 

        {
          peg$currPos = s0;
          s0 = peg$FAILED;}} else 

      {
        peg$currPos = s0;
        s0 = peg$FAILED;}

      peg$silentFails--;
      if (s0 === peg$FAILED) {
        s1 = peg$FAILED;
        if (peg$silentFails === 0) {peg$fail(peg$c65);}}


      return s0;}


    function peg$parsedirection() {
      var s0, s1;

      peg$silentFails++;
      if (input.substr(peg$currPos, 3) === peg$c75) {
        s0 = peg$c75;
        peg$currPos += 3;} else 
      {
        s0 = peg$FAILED;
        if (peg$silentFails === 0) {peg$fail(peg$c76);}}

      if (s0 === peg$FAILED) {
        if (input.substr(peg$currPos, 2) === peg$c77) {
          s0 = peg$c77;
          peg$currPos += 2;} else 
        {
          s0 = peg$FAILED;
          if (peg$silentFails === 0) {peg$fail(peg$c78);}}

        if (s0 === peg$FAILED) {
          if (input.substr(peg$currPos, 3) === peg$c79) {
            s0 = peg$c79;
            peg$currPos += 3;} else 
          {
            s0 = peg$FAILED;
            if (peg$silentFails === 0) {peg$fail(peg$c80);}}}}



      peg$silentFails--;
      if (s0 === peg$FAILED) {
        s1 = peg$FAILED;
        if (peg$silentFails === 0) {peg$fail(peg$c74);}}


      return s0;}


    function peg$parsedataDefinition() {
      var s0, s1, s2, s3, s4, s5, s6, s7, s8, s9, s10, s11;

      peg$silentFails++;
      s0 = peg$currPos;
      s1 = peg$parse_();
      if (s1 !== peg$FAILED) {
        if (input.substr(peg$currPos, 4) === peg$c81) {
          s2 = peg$c81;
          peg$currPos += 4;} else 
        {
          s2 = peg$FAILED;
          if (peg$silentFails === 0) {peg$fail(peg$c82);}}

        if (s2 !== peg$FAILED) {
          s3 = peg$parse_();
          if (s3 !== peg$FAILED) {
            s4 = peg$parsedataIdentifier();
            if (s4 !== peg$FAILED) {
              s5 = peg$parse_();
              if (s5 !== peg$FAILED) {
                s6 = peg$currPos;
                s7 = peg$parse_();
                if (s7 !== peg$FAILED) {
                  if (input.substr(peg$currPos, 4) === peg$c15) {
                    s8 = peg$c15;
                    peg$currPos += 4;} else 
                  {
                    s8 = peg$FAILED;
                    if (peg$silentFails === 0) {peg$fail(peg$c16);}}

                  if (s8 !== peg$FAILED) {
                    s9 = peg$parse_();
                    if (s9 !== peg$FAILED) {
                      s10 = peg$parsedefinitions();
                      if (s10 !== peg$FAILED) {
                        peg$savedPos = s6;
                        s7 = peg$c17(s4, s10);
                        s6 = s7;} else 
                      {
                        peg$currPos = s6;
                        s6 = peg$FAILED;}} else 

                    {
                      peg$currPos = s6;
                      s6 = peg$FAILED;}} else 

                  {
                    peg$currPos = s6;
                    s6 = peg$FAILED;}} else 

                {
                  peg$currPos = s6;
                  s6 = peg$FAILED;}

                if (s6 === peg$FAILED) {
                  s6 = null;}

                if (s6 !== peg$FAILED) {
                  s7 = peg$parse_();
                  if (s7 !== peg$FAILED) {
                    if (input.substr(peg$currPos, 2) === peg$c18) {
                      s8 = peg$c18;
                      peg$currPos += 2;} else 
                    {
                      s8 = peg$FAILED;
                      if (peg$silentFails === 0) {peg$fail(peg$c19);}}

                    if (s8 !== peg$FAILED) {
                      s9 = peg$parse_();
                      if (s9 !== peg$FAILED) {
                        s10 = peg$parsedata();
                        if (s10 !== peg$FAILED) {
                          s11 = peg$parse_();
                          if (s11 !== peg$FAILED) {
                            peg$savedPos = s0;
                            s1 = peg$c83(s4, s6, s10);
                            s0 = s1;} else 
                          {
                            peg$currPos = s0;
                            s0 = peg$FAILED;}} else 

                        {
                          peg$currPos = s0;
                          s0 = peg$FAILED;}} else 

                      {
                        peg$currPos = s0;
                        s0 = peg$FAILED;}} else 

                    {
                      peg$currPos = s0;
                      s0 = peg$FAILED;}} else 

                  {
                    peg$currPos = s0;
                    s0 = peg$FAILED;}} else 

                {
                  peg$currPos = s0;
                  s0 = peg$FAILED;}} else 

              {
                peg$currPos = s0;
                s0 = peg$FAILED;}} else 

            {
              peg$currPos = s0;
              s0 = peg$FAILED;}} else 

          {
            peg$currPos = s0;
            s0 = peg$FAILED;}} else 

        {
          peg$currPos = s0;
          s0 = peg$FAILED;}} else 

      {
        peg$currPos = s0;
        s0 = peg$FAILED;}

      peg$silentFails--;
      if (s0 === peg$FAILED) {
        s1 = peg$FAILED;
        if (peg$silentFails === 0) {peg$fail(peg$c36);}}


      return s0;}


    function peg$parsedata() {
      var s0, s1;

      peg$silentFails++;
      s0 = peg$parsedataAtomic();
      if (s0 === peg$FAILED) {
        s0 = peg$parsedataComposite();
        if (s0 === peg$FAILED) {
          s0 = peg$parsedataArray();
          if (s0 === peg$FAILED) {
            s0 = peg$parsedataFunction();
            if (s0 === peg$FAILED) {
              s0 = peg$parsedataOperation();}}}}




      peg$silentFails--;
      if (s0 === peg$FAILED) {
        s1 = peg$FAILED;
        if (peg$silentFails === 0) {peg$fail(peg$c84);}}


      return s0;}


    function peg$parsedataOperation() {
      var s0, s1, s2, s3, s4, s5, s6, s7, s8, s9, s10, s11;

      peg$silentFails++;
      s0 = peg$currPos;
      s1 = peg$parsedataOperator();
      if (s1 !== peg$FAILED) {
        s2 = peg$parse_();
        if (s2 !== peg$FAILED) {
          if (input.charCodeAt(peg$currPos) === 40) {
            s3 = peg$c22;
            peg$currPos++;} else 
          {
            s3 = peg$FAILED;
            if (peg$silentFails === 0) {peg$fail(peg$c23);}}

          if (s3 !== peg$FAILED) {
            s4 = peg$parse_();
            if (s4 !== peg$FAILED) {
              s5 = peg$parsedata();
              if (s5 !== peg$FAILED) {
                s6 = [];
                s7 = peg$currPos;
                s8 = peg$parse_();
                if (s8 !== peg$FAILED) {
                  if (input.charCodeAt(peg$currPos) === 44) {
                    s9 = peg$c42;
                    peg$currPos++;} else 
                  {
                    s9 = peg$FAILED;
                    if (peg$silentFails === 0) {peg$fail(peg$c43);}}

                  if (s9 !== peg$FAILED) {
                    s10 = peg$parse_();
                    if (s10 !== peg$FAILED) {
                      s11 = peg$parsedata();
                      if (s11 !== peg$FAILED) {
                        peg$savedPos = s7;
                        s8 = peg$c44(s1, s5, s11);
                        s7 = s8;} else 
                      {
                        peg$currPos = s7;
                        s7 = peg$FAILED;}} else 

                    {
                      peg$currPos = s7;
                      s7 = peg$FAILED;}} else 

                  {
                    peg$currPos = s7;
                    s7 = peg$FAILED;}} else 

                {
                  peg$currPos = s7;
                  s7 = peg$FAILED;}

                while (s7 !== peg$FAILED) {
                  s6.push(s7);
                  s7 = peg$currPos;
                  s8 = peg$parse_();
                  if (s8 !== peg$FAILED) {
                    if (input.charCodeAt(peg$currPos) === 44) {
                      s9 = peg$c42;
                      peg$currPos++;} else 
                    {
                      s9 = peg$FAILED;
                      if (peg$silentFails === 0) {peg$fail(peg$c43);}}

                    if (s9 !== peg$FAILED) {
                      s10 = peg$parse_();
                      if (s10 !== peg$FAILED) {
                        s11 = peg$parsedata();
                        if (s11 !== peg$FAILED) {
                          peg$savedPos = s7;
                          s8 = peg$c44(s1, s5, s11);
                          s7 = s8;} else 
                        {
                          peg$currPos = s7;
                          s7 = peg$FAILED;}} else 

                      {
                        peg$currPos = s7;
                        s7 = peg$FAILED;}} else 

                    {
                      peg$currPos = s7;
                      s7 = peg$FAILED;}} else 

                  {
                    peg$currPos = s7;
                    s7 = peg$FAILED;}}


                if (s6 !== peg$FAILED) {
                  s7 = peg$parse_();
                  if (s7 !== peg$FAILED) {
                    if (input.charCodeAt(peg$currPos) === 41) {
                      s8 = peg$c24;
                      peg$currPos++;} else 
                    {
                      s8 = peg$FAILED;
                      if (peg$silentFails === 0) {peg$fail(peg$c25);}}

                    if (s8 !== peg$FAILED) {
                      peg$savedPos = s0;
                      s1 = peg$c86(s1, s5, s6);
                      s0 = s1;} else 
                    {
                      peg$currPos = s0;
                      s0 = peg$FAILED;}} else 

                  {
                    peg$currPos = s0;
                    s0 = peg$FAILED;}} else 

                {
                  peg$currPos = s0;
                  s0 = peg$FAILED;}} else 

              {
                peg$currPos = s0;
                s0 = peg$FAILED;}} else 

            {
              peg$currPos = s0;
              s0 = peg$FAILED;}} else 

          {
            peg$currPos = s0;
            s0 = peg$FAILED;}} else 

        {
          peg$currPos = s0;
          s0 = peg$FAILED;}} else 

      {
        peg$currPos = s0;
        s0 = peg$FAILED;}

      peg$silentFails--;
      if (s0 === peg$FAILED) {
        s1 = peg$FAILED;
        if (peg$silentFails === 0) {peg$fail(peg$c85);}}


      return s0;}


    function peg$parsedataOperator() {
      var s0, s1;

      peg$silentFails++;
      if (input.substr(peg$currPos, 5) === peg$c57) {
        s0 = peg$c57;
        peg$currPos += 5;} else 
      {
        s0 = peg$FAILED;
        if (peg$silentFails === 0) {peg$fail(peg$c58);}}

      if (s0 === peg$FAILED) {
        if (input.substr(peg$currPos, 12) === peg$c59) {
          s0 = peg$c59;
          peg$currPos += 12;} else 
        {
          s0 = peg$FAILED;
          if (peg$silentFails === 0) {peg$fail(peg$c60);}}

        if (s0 === peg$FAILED) {
          if (input.substr(peg$currPos, 10) === peg$c61) {
            s0 = peg$c61;
            peg$currPos += 10;} else 
          {
            s0 = peg$FAILED;
            if (peg$silentFails === 0) {peg$fail(peg$c62);}}}}



      peg$silentFails--;
      if (s0 === peg$FAILED) {
        s1 = peg$FAILED;
        if (peg$silentFails === 0) {peg$fail(peg$c87);}}


      return s0;}


    function peg$parsedataAtomic() {
      var s0, s1;

      peg$silentFails++;
      s0 = peg$currPos;
      s1 = peg$parsedataIdentifier();
      if (s1 !== peg$FAILED) {
        peg$savedPos = s0;
        s1 = peg$c89(s1);}

      s0 = s1;
      peg$silentFails--;
      if (s0 === peg$FAILED) {
        s1 = peg$FAILED;
        if (peg$silentFails === 0) {peg$fail(peg$c88);}}


      return s0;}


    function peg$parsedataComposite() {
      var s0, s1, s2, s3, s4, s5, s6, s7, s8, s9, s10, s11, s12, s13, s14;

      peg$silentFails++;
      s0 = peg$currPos;
      if (input.charCodeAt(peg$currPos) === 123) {
        s1 = peg$c66;
        peg$currPos++;} else 
      {
        s1 = peg$FAILED;
        if (peg$silentFails === 0) {peg$fail(peg$c67);}}

      if (s1 !== peg$FAILED) {
        s2 = peg$parse_();
        if (s2 !== peg$FAILED) {
          s3 = peg$currPos;
          s4 = peg$parsekeyIdentifier();
          if (s4 !== peg$FAILED) {
            s5 = peg$parse_();
            if (s5 !== peg$FAILED) {
              if (input.charCodeAt(peg$currPos) === 58) {
                s6 = peg$c26;
                peg$currPos++;} else 
              {
                s6 = peg$FAILED;
                if (peg$silentFails === 0) {peg$fail(peg$c27);}}

              if (s6 !== peg$FAILED) {
                s7 = peg$parse_();
                if (s7 !== peg$FAILED) {
                  s8 = peg$parsedata();
                  if (s8 !== peg$FAILED) {
                    peg$savedPos = s3;
                    s4 = peg$c91(s4, s8);
                    s3 = s4;} else 
                  {
                    peg$currPos = s3;
                    s3 = peg$FAILED;}} else 

                {
                  peg$currPos = s3;
                  s3 = peg$FAILED;}} else 

              {
                peg$currPos = s3;
                s3 = peg$FAILED;}} else 

            {
              peg$currPos = s3;
              s3 = peg$FAILED;}} else 

          {
            peg$currPos = s3;
            s3 = peg$FAILED;}

          if (s3 !== peg$FAILED) {
            s4 = peg$parse_();
            if (s4 !== peg$FAILED) {
              s5 = [];
              s6 = peg$currPos;
              if (input.charCodeAt(peg$currPos) === 44) {
                s7 = peg$c42;
                peg$currPos++;} else 
              {
                s7 = peg$FAILED;
                if (peg$silentFails === 0) {peg$fail(peg$c43);}}

              if (s7 !== peg$FAILED) {
                s8 = peg$parse_();
                if (s8 !== peg$FAILED) {
                  s9 = peg$currPos;
                  s10 = peg$parsekeyIdentifier();
                  if (s10 !== peg$FAILED) {
                    s11 = peg$parse_();
                    if (s11 !== peg$FAILED) {
                      if (input.charCodeAt(peg$currPos) === 58) {
                        s12 = peg$c26;
                        peg$currPos++;} else 
                      {
                        s12 = peg$FAILED;
                        if (peg$silentFails === 0) {peg$fail(peg$c27);}}

                      if (s12 !== peg$FAILED) {
                        s13 = peg$parse_();
                        if (s13 !== peg$FAILED) {
                          s14 = peg$parsedata();
                          if (s14 !== peg$FAILED) {
                            peg$savedPos = s9;
                            s10 = peg$c92(s3, s10, s14);
                            s9 = s10;} else 
                          {
                            peg$currPos = s9;
                            s9 = peg$FAILED;}} else 

                        {
                          peg$currPos = s9;
                          s9 = peg$FAILED;}} else 

                      {
                        peg$currPos = s9;
                        s9 = peg$FAILED;}} else 

                    {
                      peg$currPos = s9;
                      s9 = peg$FAILED;}} else 

                  {
                    peg$currPos = s9;
                    s9 = peg$FAILED;}

                  if (s9 !== peg$FAILED) {
                    s10 = peg$parse_();
                    if (s10 !== peg$FAILED) {
                      peg$savedPos = s6;
                      s7 = peg$c70(s3, s9);
                      s6 = s7;} else 
                    {
                      peg$currPos = s6;
                      s6 = peg$FAILED;}} else 

                  {
                    peg$currPos = s6;
                    s6 = peg$FAILED;}} else 

                {
                  peg$currPos = s6;
                  s6 = peg$FAILED;}} else 

              {
                peg$currPos = s6;
                s6 = peg$FAILED;}

              while (s6 !== peg$FAILED) {
                s5.push(s6);
                s6 = peg$currPos;
                if (input.charCodeAt(peg$currPos) === 44) {
                  s7 = peg$c42;
                  peg$currPos++;} else 
                {
                  s7 = peg$FAILED;
                  if (peg$silentFails === 0) {peg$fail(peg$c43);}}

                if (s7 !== peg$FAILED) {
                  s8 = peg$parse_();
                  if (s8 !== peg$FAILED) {
                    s9 = peg$currPos;
                    s10 = peg$parsekeyIdentifier();
                    if (s10 !== peg$FAILED) {
                      s11 = peg$parse_();
                      if (s11 !== peg$FAILED) {
                        if (input.charCodeAt(peg$currPos) === 58) {
                          s12 = peg$c26;
                          peg$currPos++;} else 
                        {
                          s12 = peg$FAILED;
                          if (peg$silentFails === 0) {peg$fail(peg$c27);}}

                        if (s12 !== peg$FAILED) {
                          s13 = peg$parse_();
                          if (s13 !== peg$FAILED) {
                            s14 = peg$parsedata();
                            if (s14 !== peg$FAILED) {
                              peg$savedPos = s9;
                              s10 = peg$c92(s3, s10, s14);
                              s9 = s10;} else 
                            {
                              peg$currPos = s9;
                              s9 = peg$FAILED;}} else 

                          {
                            peg$currPos = s9;
                            s9 = peg$FAILED;}} else 

                        {
                          peg$currPos = s9;
                          s9 = peg$FAILED;}} else 

                      {
                        peg$currPos = s9;
                        s9 = peg$FAILED;}} else 

                    {
                      peg$currPos = s9;
                      s9 = peg$FAILED;}

                    if (s9 !== peg$FAILED) {
                      s10 = peg$parse_();
                      if (s10 !== peg$FAILED) {
                        peg$savedPos = s6;
                        s7 = peg$c70(s3, s9);
                        s6 = s7;} else 
                      {
                        peg$currPos = s6;
                        s6 = peg$FAILED;}} else 

                    {
                      peg$currPos = s6;
                      s6 = peg$FAILED;}} else 

                  {
                    peg$currPos = s6;
                    s6 = peg$FAILED;}} else 

                {
                  peg$currPos = s6;
                  s6 = peg$FAILED;}}


              if (s5 !== peg$FAILED) {
                if (input.charCodeAt(peg$currPos) === 125) {
                  s6 = peg$c71;
                  peg$currPos++;} else 
                {
                  s6 = peg$FAILED;
                  if (peg$silentFails === 0) {peg$fail(peg$c72);}}

                if (s6 !== peg$FAILED) {
                  peg$savedPos = s0;
                  s1 = peg$c93(s3, s5);
                  s0 = s1;} else 
                {
                  peg$currPos = s0;
                  s0 = peg$FAILED;}} else 

              {
                peg$currPos = s0;
                s0 = peg$FAILED;}} else 

            {
              peg$currPos = s0;
              s0 = peg$FAILED;}} else 

          {
            peg$currPos = s0;
            s0 = peg$FAILED;}} else 

        {
          peg$currPos = s0;
          s0 = peg$FAILED;}} else 

      {
        peg$currPos = s0;
        s0 = peg$FAILED;}

      peg$silentFails--;
      if (s0 === peg$FAILED) {
        s1 = peg$FAILED;
        if (peg$silentFails === 0) {peg$fail(peg$c90);}}


      return s0;}


    function peg$parsedataArray() {
      var s0, s1, s2, s3, s4, s5;

      peg$silentFails++;
      s0 = peg$currPos;
      if (input.charCodeAt(peg$currPos) === 91) {
        s1 = peg$c95;
        peg$currPos++;} else 
      {
        s1 = peg$FAILED;
        if (peg$silentFails === 0) {peg$fail(peg$c96);}}

      if (s1 !== peg$FAILED) {
        s2 = peg$parse_();
        if (s2 !== peg$FAILED) {
          s3 = peg$parsedata();
          if (s3 !== peg$FAILED) {
            s4 = peg$parse_();
            if (s4 !== peg$FAILED) {
              if (input.charCodeAt(peg$currPos) === 93) {
                s5 = peg$c97;
                peg$currPos++;} else 
              {
                s5 = peg$FAILED;
                if (peg$silentFails === 0) {peg$fail(peg$c98);}}

              if (s5 !== peg$FAILED) {
                peg$savedPos = s0;
                s1 = peg$c99(s3);
                s0 = s1;} else 
              {
                peg$currPos = s0;
                s0 = peg$FAILED;}} else 

            {
              peg$currPos = s0;
              s0 = peg$FAILED;}} else 

          {
            peg$currPos = s0;
            s0 = peg$FAILED;}} else 

        {
          peg$currPos = s0;
          s0 = peg$FAILED;}} else 

      {
        peg$currPos = s0;
        s0 = peg$FAILED;}

      peg$silentFails--;
      if (s0 === peg$FAILED) {
        s1 = peg$FAILED;
        if (peg$silentFails === 0) {peg$fail(peg$c94);}}


      return s0;}


    function peg$parsedataFunction() {
      var s0, s1, s2, s3, s4, s5, s6, s7, s8, s9;

      peg$silentFails++;
      s0 = peg$currPos;
      if (input.charCodeAt(peg$currPos) === 123) {
        s1 = peg$c66;
        peg$currPos++;} else 
      {
        s1 = peg$FAILED;
        if (peg$silentFails === 0) {peg$fail(peg$c67);}}

      if (s1 !== peg$FAILED) {
        s2 = peg$parse_();
        if (s2 !== peg$FAILED) {
          s3 = peg$parsedata();
          if (s3 !== peg$FAILED) {
            s4 = peg$parse_();
            if (s4 !== peg$FAILED) {
              if (input.charCodeAt(peg$currPos) === 8594) {
                s5 = peg$c101;
                peg$currPos++;} else 
              {
                s5 = peg$FAILED;
                if (peg$silentFails === 0) {peg$fail(peg$c102);}}

              if (s5 === peg$FAILED) {
                if (input.substr(peg$currPos, 2) === peg$c103) {
                  s5 = peg$c103;
                  peg$currPos += 2;} else 
                {
                  s5 = peg$FAILED;
                  if (peg$silentFails === 0) {peg$fail(peg$c104);}}}


              if (s5 !== peg$FAILED) {
                s6 = peg$parse_();
                if (s6 !== peg$FAILED) {
                  s7 = peg$parsedata();
                  if (s7 !== peg$FAILED) {
                    s8 = peg$parse_();
                    if (s8 !== peg$FAILED) {
                      if (input.charCodeAt(peg$currPos) === 125) {
                        s9 = peg$c71;
                        peg$currPos++;} else 
                      {
                        s9 = peg$FAILED;
                        if (peg$silentFails === 0) {peg$fail(peg$c72);}}

                      if (s9 !== peg$FAILED) {
                        peg$savedPos = s0;
                        s1 = peg$c105(s3, s7);
                        s0 = s1;} else 
                      {
                        peg$currPos = s0;
                        s0 = peg$FAILED;}} else 

                    {
                      peg$currPos = s0;
                      s0 = peg$FAILED;}} else 

                  {
                    peg$currPos = s0;
                    s0 = peg$FAILED;}} else 

                {
                  peg$currPos = s0;
                  s0 = peg$FAILED;}} else 

              {
                peg$currPos = s0;
                s0 = peg$FAILED;}} else 

            {
              peg$currPos = s0;
              s0 = peg$FAILED;}} else 

          {
            peg$currPos = s0;
            s0 = peg$FAILED;}} else 

        {
          peg$currPos = s0;
          s0 = peg$FAILED;}} else 

      {
        peg$currPos = s0;
        s0 = peg$FAILED;}

      peg$silentFails--;
      if (s0 === peg$FAILED) {
        s1 = peg$FAILED;
        if (peg$silentFails === 0) {peg$fail(peg$c100);}}


      return s0;}


    function peg$parseoperatorIdentifier() {
      var s0, s1, s2;

      peg$silentFails++;
      s0 = peg$currPos;
      s1 = [];
      if (peg$c107.test(input.charAt(peg$currPos))) {
        s2 = input.charAt(peg$currPos);
        peg$currPos++;} else 
      {
        s2 = peg$FAILED;
        if (peg$silentFails === 0) {peg$fail(peg$c108);}}

      if (s2 !== peg$FAILED) {
        while (s2 !== peg$FAILED) {
          s1.push(s2);
          if (peg$c107.test(input.charAt(peg$currPos))) {
            s2 = input.charAt(peg$currPos);
            peg$currPos++;} else 
          {
            s2 = peg$FAILED;
            if (peg$silentFails === 0) {peg$fail(peg$c108);}}}} else 


      {
        s1 = peg$FAILED;}

      if (s1 !== peg$FAILED) {
        peg$savedPos = s0;
        s1 = peg$c109(s1);}

      s0 = s1;
      peg$silentFails--;
      if (s0 === peg$FAILED) {
        s1 = peg$FAILED;
        if (peg$silentFails === 0) {peg$fail(peg$c106);}}


      return s0;}


    function peg$parseinterfaceIdentifier() {
      var s0, s1, s2, s3;

      peg$silentFails++;
      s0 = peg$currPos;
      if (peg$c111.test(input.charAt(peg$currPos))) {
        s1 = input.charAt(peg$currPos);
        peg$currPos++;} else 
      {
        s1 = peg$FAILED;
        if (peg$silentFails === 0) {peg$fail(peg$c112);}}

      if (s1 !== peg$FAILED) {
        s2 = [];
        if (peg$c113.test(input.charAt(peg$currPos))) {
          s3 = input.charAt(peg$currPos);
          peg$currPos++;} else 
        {
          s3 = peg$FAILED;
          if (peg$silentFails === 0) {peg$fail(peg$c114);}}

        while (s3 !== peg$FAILED) {
          s2.push(s3);
          if (peg$c113.test(input.charAt(peg$currPos))) {
            s3 = input.charAt(peg$currPos);
            peg$currPos++;} else 
          {
            s3 = peg$FAILED;
            if (peg$silentFails === 0) {peg$fail(peg$c114);}}}


        if (s2 !== peg$FAILED) {
          peg$savedPos = s0;
          s1 = peg$c115(s1, s2);
          s0 = s1;} else 
        {
          peg$currPos = s0;
          s0 = peg$FAILED;}} else 

      {
        peg$currPos = s0;
        s0 = peg$FAILED;}

      peg$silentFails--;
      if (s0 === peg$FAILED) {
        s1 = peg$FAILED;
        if (peg$silentFails === 0) {peg$fail(peg$c110);}}


      return s0;}


    function peg$parsedataIdentifier() {
      var s0, s1, s2, s3;

      peg$silentFails++;
      s0 = peg$currPos;
      if (peg$c111.test(input.charAt(peg$currPos))) {
        s1 = input.charAt(peg$currPos);
        peg$currPos++;} else 
      {
        s1 = peg$FAILED;
        if (peg$silentFails === 0) {peg$fail(peg$c112);}}

      if (s1 !== peg$FAILED) {
        s2 = [];
        if (peg$c113.test(input.charAt(peg$currPos))) {
          s3 = input.charAt(peg$currPos);
          peg$currPos++;} else 
        {
          s3 = peg$FAILED;
          if (peg$silentFails === 0) {peg$fail(peg$c114);}}

        while (s3 !== peg$FAILED) {
          s2.push(s3);
          if (peg$c113.test(input.charAt(peg$currPos))) {
            s3 = input.charAt(peg$currPos);
            peg$currPos++;} else 
          {
            s3 = peg$FAILED;
            if (peg$silentFails === 0) {peg$fail(peg$c114);}}}


        if (s2 !== peg$FAILED) {
          peg$savedPos = s0;
          s1 = peg$c115(s1, s2);
          s0 = s1;} else 
        {
          peg$currPos = s0;
          s0 = peg$FAILED;}} else 

      {
        peg$currPos = s0;
        s0 = peg$FAILED;}

      peg$silentFails--;
      if (s0 === peg$FAILED) {
        s1 = peg$FAILED;
        if (peg$silentFails === 0) {peg$fail(peg$c116);}}


      return s0;}


    function peg$parsevariableIdentifier() {
      var s0, s1, s2, s3;

      peg$silentFails++;
      s0 = peg$currPos;
      if (peg$c118.test(input.charAt(peg$currPos))) {
        s1 = input.charAt(peg$currPos);
        peg$currPos++;} else 
      {
        s1 = peg$FAILED;
        if (peg$silentFails === 0) {peg$fail(peg$c119);}}

      if (s1 !== peg$FAILED) {
        s2 = [];
        if (peg$c113.test(input.charAt(peg$currPos))) {
          s3 = input.charAt(peg$currPos);
          peg$currPos++;} else 
        {
          s3 = peg$FAILED;
          if (peg$silentFails === 0) {peg$fail(peg$c114);}}

        while (s3 !== peg$FAILED) {
          s2.push(s3);
          if (peg$c113.test(input.charAt(peg$currPos))) {
            s3 = input.charAt(peg$currPos);
            peg$currPos++;} else 
          {
            s3 = peg$FAILED;
            if (peg$silentFails === 0) {peg$fail(peg$c114);}}}


        if (s2 !== peg$FAILED) {
          peg$savedPos = s0;
          s1 = peg$c115(s1, s2);
          s0 = s1;} else 
        {
          peg$currPos = s0;
          s0 = peg$FAILED;}} else 

      {
        peg$currPos = s0;
        s0 = peg$FAILED;}

      peg$silentFails--;
      if (s0 === peg$FAILED) {
        s1 = peg$FAILED;
        if (peg$silentFails === 0) {peg$fail(peg$c117);}}


      return s0;}


    function peg$parsekeyIdentifier() {
      var s0, s1, s2, s3;

      peg$silentFails++;
      s0 = peg$currPos;
      if (peg$c121.test(input.charAt(peg$currPos))) {
        s1 = input.charAt(peg$currPos);
        peg$currPos++;} else 
      {
        s1 = peg$FAILED;
        if (peg$silentFails === 0) {peg$fail(peg$c122);}}

      if (s1 !== peg$FAILED) {
        s2 = [];
        if (peg$c113.test(input.charAt(peg$currPos))) {
          s3 = input.charAt(peg$currPos);
          peg$currPos++;} else 
        {
          s3 = peg$FAILED;
          if (peg$silentFails === 0) {peg$fail(peg$c114);}}

        while (s3 !== peg$FAILED) {
          s2.push(s3);
          if (peg$c113.test(input.charAt(peg$currPos))) {
            s3 = input.charAt(peg$currPos);
            peg$currPos++;} else 
          {
            s3 = peg$FAILED;
            if (peg$silentFails === 0) {peg$fail(peg$c114);}}}


        if (s2 !== peg$FAILED) {
          peg$savedPos = s0;
          s1 = peg$c115(s1, s2);
          s0 = s1;} else 
        {
          peg$currPos = s0;
          s0 = peg$FAILED;}} else 

      {
        peg$currPos = s0;
        s0 = peg$FAILED;}

      peg$silentFails--;
      if (s0 === peg$FAILED) {
        s1 = peg$FAILED;
        if (peg$silentFails === 0) {peg$fail(peg$c120);}}


      return s0;}


    function peg$parsefunctionIdentifier() {
      var s0, s1, s2, s3;

      peg$silentFails++;
      s0 = peg$currPos;
      if (peg$c124.test(input.charAt(peg$currPos))) {
        s1 = input.charAt(peg$currPos);
        peg$currPos++;} else 
      {
        s1 = peg$FAILED;
        if (peg$silentFails === 0) {peg$fail(peg$c125);}}

      if (s1 !== peg$FAILED) {
        s2 = [];
        if (peg$c126.test(input.charAt(peg$currPos))) {
          s3 = input.charAt(peg$currPos);
          peg$currPos++;} else 
        {
          s3 = peg$FAILED;
          if (peg$silentFails === 0) {peg$fail(peg$c127);}}

        while (s3 !== peg$FAILED) {
          s2.push(s3);
          if (peg$c126.test(input.charAt(peg$currPos))) {
            s3 = input.charAt(peg$currPos);
            peg$currPos++;} else 
          {
            s3 = peg$FAILED;
            if (peg$silentFails === 0) {peg$fail(peg$c127);}}}


        if (s2 !== peg$FAILED) {
          peg$savedPos = s0;
          s1 = peg$c115(s1, s2);
          s0 = s1;} else 
        {
          peg$currPos = s0;
          s0 = peg$FAILED;}} else 

      {
        peg$currPos = s0;
        s0 = peg$FAILED;}

      peg$silentFails--;
      if (s0 === peg$FAILED) {
        s1 = peg$FAILED;
        if (peg$silentFails === 0) {peg$fail(peg$c123);}}


      return s0;}


    function peg$parse_() {
      var s0, s1;

      peg$silentFails++;
      s0 = [];
      if (peg$c129.test(input.charAt(peg$currPos))) {
        s1 = input.charAt(peg$currPos);
        peg$currPos++;} else 
      {
        s1 = peg$FAILED;
        if (peg$silentFails === 0) {peg$fail(peg$c130);}}

      while (s1 !== peg$FAILED) {
        s0.push(s1);
        if (peg$c129.test(input.charAt(peg$currPos))) {
          s1 = input.charAt(peg$currPos);
          peg$currPos++;} else 
        {
          s1 = peg$FAILED;
          if (peg$silentFails === 0) {peg$fail(peg$c130);}}}


      peg$silentFails--;
      if (s0 === peg$FAILED) {
        s1 = peg$FAILED;
        if (peg$silentFails === 0) {peg$fail(peg$c128);}}


      return s0;}



    var fs = require('fs');

    var resolver = options.resolver;

    function mergeExpression(elements) {
      var res = { operator: '', operand: [] };
      for (var i = 0; i < elements.length; i++) {
        if (elements[i].operand !== undefined && elements[i].operand !== null) {
          res.operand.push(elements[i].operand);
          res.operator = res.operator + '$';}

        if (elements[i].operator !== undefined && elements[i].operator !== null) {
          res.operator = res.operator + elements[i].operator;}}


      return res;}


    function mergeSignature(elements) {
      var res = { operator: '', operand: [] };
      for (var i = 0; i < elements.length; i++) {
        if (elements[i].operand !== undefined && elements[i].operand !== null) {
          res.operand.push(elements[i].operand);
          res.operator = res.operator + '$';}

        if (elements[i].operator !== undefined && elements[i].operator !== null) {
          res.operator = res.operator + elements[i].operator;}}


      return res;}


    function mergeElements(first, rest) {
      var res = [];
      if (rest !== undefined && rest !== null) {
        res = rest;}

      res.unshift(first);
      return res;}


    function flatten(table) {
      var res = [];
      for (var i = 0; i < table.length; i++) {
        res = res.concat(table[i]);}

      return res;}



    peg$result = peg$startRuleFunction();

    if (peg$result !== peg$FAILED && peg$currPos === input.length) {
      return peg$result;} else 
    {
      if (peg$result !== peg$FAILED && peg$currPos < input.length) {
        peg$fail({ type: "end", description: "end of input" });}


      throw peg$buildException(
      null, 
      peg$maxFailExpected, 
      peg$maxFailPos < input.length ? input.charAt(peg$maxFailPos) : null, 
      peg$maxFailPos < input.length ? 
      peg$computeLocation(peg$maxFailPos, peg$maxFailPos + 1) : 
      peg$computeLocation(peg$maxFailPos, peg$maxFailPos));}}




  return { 
    SyntaxError: peg$SyntaxError, 
    parse: peg$parse };})();