import peggy from "peggy";
import * as path from "path";
import * as fs from "fs";
import _ from "lodash";

const srcDir = path.resolve(import.meta.dir, "src");
const exampleDir = path.resolve(import.meta.dir, "example/ok");

const parserGrammar = await Bun.file(path.join(srcDir, "parser.pegjs")).text();
const parserSource = peggy.generate(parserGrammar, {
  allowedStartRules: [
    "start",
    "interaction",
    "interfac",
    "data",
    "interactionDefinition",
  ],
  output: "source",
  format: "bare",
});
await Bun.write(
  path.join(srcDir, "parser.js"),
  `// @generated by build.ts using Peggy\nexport default ${parserSource}\n`,
);

const operatorGrammar = await Bun.file(
  path.join(srcDir, "operator.pegjs"),
).text();
const operatorSource = peggy.generate(operatorGrammar, {
  allowedStartRules: ["start"],
  output: "source",
  format: "bare",
});
await Bun.write(
  path.join(srcDir, "operator.js"),
  `// @generated by build.ts using Peggy\nexport default ${operatorSource}\n`,
);

const commonHeader = await Bun.file(
  path.join(exampleDir, "common.lidl.js"),
).text();

const exampleSubdirs = fs
  .readdirSync(exampleDir)
  .map((x) => path.join(exampleDir, x))
  .filter((ffile) => fs.statSync(ffile).isDirectory());

const examples = await Promise.all(
  exampleSubdirs.map(async (ffile) => ({
    name: _.startCase(path.basename(ffile)),
    fileName: ffile,
    code: await Bun.file(path.join(ffile, "code.lidl")).text(),
    scenario: await Bun.file(path.join(ffile, "scenario.json")).text(),
  })),
);

const examplesContent = `// @generated by build.ts
export default {
  header: ${JSON.stringify(commonHeader)},
  lidl: ${JSON.stringify(examples, null, 2)},
};
`;
await Bun.write(path.join(srcDir, "examples.ts"), examplesContent);

console.log("Build complete: parser.js, operator.js, examples.ts generated.");
